/* eslint-disable */
// Auto-generated by scripts/generate-v2-tw-quiz.mjs
// Source: /Users/pensoair/Library/Mobile Documents/iCloud~md~obsidian/Documents/Penso-OS/07_專案工坊/Subdomain_kiwimu.com/Kiwimu_MBTI_Lab_內容庫/2026_H1_跨國升級版/MBTI_Question_Bank_2026_Taiwan.md

export type V2QuestionDimension = 'EI' | 'SN' | 'TF' | 'JP' | 'AT';
export type V2QuestionValue = 'E' | 'I' | 'S' | 'N' | 'T' | 'F' | 'J' | 'P' | 'A' | 'Turbulent';

export interface V2GeneratedQuestionOption {
  id: 'a' | 'b';
  label: string;
  value: V2QuestionValue;
}

export interface V2GeneratedQuestion {
  id: number;
  questionId: string;
  country: string;
  dimension: V2QuestionDimension;
  text: string;
  options: [V2GeneratedQuestionOption, V2GeneratedQuestionOption];
  culturalNote: string;
  weight: number;
}

export const V2_TW_QUESTION_SOURCE = "/Users/pensoair/Library/Mobile Documents/iCloud~md~obsidian/Documents/Penso-OS/07_專案工坊/Subdomain_kiwimu.com/Kiwimu_MBTI_Lab_內容庫/2026_H1_跨國升級版/MBTI_Question_Bank_2026_Taiwan.md";

export const V2_TAIWAN_QUESTIONS: V2GeneratedQuestion[] = [
  {
    id: 1,
    questionId: "Q01",
    country: "Taiwan",
    dimension: "EI",
    text: "經歷了連續五天高壓轟炸的工作/學校生活，好不容易迎來週末，你大腦直覺的「回血機制 」是：",
    options: [
      { id: 'a', label: "立刻開啟「社交高手 / 氣氛製造機」模式揪團！出去見朋友、跑局、吸收外面的新鮮空氣，才是真正的「光合作用」與充電。", value: "E" },
      { id: 'b', label: "啟動「社交斷食」與勿擾模式。我需要躲進專屬的「能量恢復艙」（追劇、看書或發呆），享受專屬的「Me-time 時光」。", value: "I" },
    ],
    culturalNote: "E人出門是「光合作用」，I人獨處是「Me-time / 能量恢復艙」。",
    weight: 2,
  },
  {
    id: 2,
    questionId: "Q02",
    country: "Taiwan",
    dimension: "EI",
    text: "來到一個有七成以上都是陌生人的聚會或派對，你通常的「生存模式」是：",
    options: [
      { id: 'a', label: "自帶「熟人濾鏡」！覺得大家都是還沒認識的朋友，主動破冰搭話完全沒障礙，是全場最罩的「氣氛製造機」。", value: "E" },
      { id: 'b', label: "啟動「保護色」模式。默默待在角落觀察，絕對需要緊緊黏著認識的朋友（俗稱「社交導盲犬」），等別人來搭話。", value: "I" },
    ],
    culturalNote: "社交導盲犬是極具共鳴的 I 人派對生存迷因。",
    weight: 1,
  },
  {
    id: 3,
    questionId: "Q03",
    country: "Taiwan",
    dimension: "EI",
    text: "難得的休假日，如果朋友突然臨時約你「等一下要不要去喝杯咖啡/逛個街？」，你的大腦第一反應是：",
    options: [
      { id: 'a', label: "立刻換衣服出門！主打一個「說走就走」的高機動性。休假日就是要行程塞滿滿，臨時的邀約反而像開盲盒一樣充滿驚喜。", value: "E" },
      { id: 'b', label: "大腦警報大響！出門是需要「提前心理建設」的。如果今天已經設定是「居家模式」，就算是天王老子來約，我也會溫柔且堅定地婉拒。", value: "I" },
    ],
    culturalNote: "強調 I 人出門前的「心理建設」與時間邊界感。",
    weight: 1,
  },
  {
    id: 4,
    questionId: "Q04",
    country: "Taiwan",
    dimension: "EI",
    text: "打開你的 Instagram 或 Threads，你最真實的「社群活躍狀態」通常是：",
    options: [
      { id: 'a', label: "限時動態常常縮到變成「螞蟻大小（點點點）」！主打一個「分享欲爆棚」，吃到好吃的、看到好笑的，立刻發動態或到處留言互動。", value: "E" },
      { id: 'b', label: "專業的「潛水員」或「幽靈人口」。版面幾乎長草，平常只看不發，或者只把真實的心情發在人極少的「摯友圈」或「小帳」裡。", value: "I" },
    ],
    culturalNote: "螞蟻限動 vs 摯友圈/小帳，完美區分社群表達欲。",
    weight: 1,
  },
  {
    id: 5,
    questionId: "Q05",
    country: "Taiwan",
    dimension: "EI",
    text: "在很多人一起聊天的 LINE 群組或是實體聚會中，你通常扮演什麼樣的發言角色？",
    options: [
      { id: 'a', label: "極度害怕空氣突然安靜！大腦習慣「邊講邊想」，喜歡丟出各種點子跟大家碰撞，是維持熱絡氣氛的「話題發動機」。", value: "E" },
      { id: 'b', label: "大腦習慣「想好再講」。通常會先默默觀察、吸收大家的資訊，等到關鍵時刻才開口，主打一個重質不重量的「精準狙擊手 / 總結大師」。", value: "I" },
    ],
    culturalNote: "外部處理器(話題發動機) vs 內部處理器(總結大師)。",
    weight: 1,
  },
  {
    id: 6,
    questionId: "Q06",
    country: "Taiwan",
    dimension: "EI",
    text: "在人際交往中，你通常是如何定義「好朋友」並建立深厚信任感的？",
    options: [
      { id: 'a', label: "交友濾鏡全開，主打一個天生的「自來熟」！喜歡透過頻繁的互動、一起玩樂來升級交情，是能把不同圈子串連起來、超好揪的「朋友富翁」。", value: "E" },
      { id: 'b', label: "交友自帶「嚴格的篩選機制」。不輕易交心，但只要把你放進「極少數的摯友圈」，就是一輩子的事。主打一個「靈魂伴侶級」的深度陪伴。", value: "I" },
    ],
    culturalNote: "朋友富翁 vs 嚴格篩選的靈魂伴侶，雙向肯定交友觀。",
    weight: 1,
  },
  {
    id: 7,
    questionId: "Q07",
    country: "Taiwan",
    dimension: "EI",
    text: "最近發現了一間超級想去的熱門餐廳或有趣的展覽，你大腦第一時間的「行動直覺」是：",
    options: [
      { id: 'a', label: "立刻丟到群組大喊「誰要一起去！」主打一個「獨樂樂不如眾樂樂」。對你來說，跟一群人共同分享那個情緒，快樂值才會無限翻倍。", value: "E" },
      { id: 'b', label: "第一念頭是安排一場「自己的獨旅 / Me-time」，或是只約一個最懂我的摯友。更享受不被打擾、按自己步調去感受的「高質量私密時光」。", value: "I" },
    ],
    culturalNote: "能量的流動：群體共振 vs 私密體驗。",
    weight: 1,
  },
  {
    id: 8,
    questionId: "Q08",
    country: "Taiwan",
    dimension: "EI",
    text: "生活中遇到瓶頸、煩惱，或是需要做一個重要決定時，你大腦最習慣的「找答案方式」是：",
    options: [
      { id: 'a', label: "透過「對外連線」來找解方！習慣打給朋友大聊特聊，透過一來一往的互動與共鳴來「吸取電力」跟靈感，話講完了，思緒也就通了。", value: "E" },
      { id: 'b', label: "數位時代的「獨立研究員」！瘋狂爬文、看論壇，甚至「打開 AI 跟它深度討論」。等自己把資訊消化完得出結論後，才會跟別人說。", value: "I" },
    ],
    culturalNote: "引入「與AI深度討論」的現代 I 人絕佳解方機制。",
    weight: 1,
  },
  {
    id: 9,
    questionId: "Q09",
    country: "Taiwan",
    dimension: "SN",
    text: "當朋友興沖沖地跑來跟你講一個八卦或故事時，你大腦會優先捕捉什麼資訊？",
    options: [
      { id: 'a', label: "嚴謹的「細節控 / 實體還原大師」。大腦會自動抓取人事時地物，想知道確切的對話內容、發生的先後順序，喜歡具體還原現場。", value: "S" },
      { id: 'b', label: "腦洞大開的「通靈大師 / 弦外之音解碼器」。重點不在細節，而是對方「為什麼」這樣做，擅長看透背後的動機與潛台詞。", value: "N" },
    ],
    culturalNote: "細節控還原現場 vs 尋找背後意義。",
    weight: 2,
  },
  {
    id: 10,
    questionId: "Q10",
    country: "Taiwan",
    dimension: "SN",
    text: "站在窗邊看著一張安靜樹林的照片，你腦中第一個浮現的念頭比較接近：",
    options: [
      { id: 'a', label: "著眼於具體細節：「實際溫度大概多少？葉子顏色適合什麼濾鏡？空氣聞起來像雨後嗎？」", value: "S" },
      { id: 'b', label: "充滿故事性的聯想：「這根本自帶主角感…如果我走進去，人生會不會直接翻盤？」", value: "N" },
    ],
    culturalNote: "五感與現實細節 vs 充滿想像力的主角感。",
    weight: 1,
  },
  {
    id: 11,
    questionId: "Q11",
    country: "Taiwan",
    dimension: "SN",
    text: "學一個全新的App或工具（例如剪片軟體或AI prompt）時，你通常：",
    options: [
      { id: 'a', label: "穩紮穩打的「實戰派」。先看教學，一步步照做，確認每個功能在哪裡再自己動手玩。", value: "S" },
      { id: 'b', label: "縱觀全局的「直覺派」。直接打開亂點，邊玩邊摸索它的邏輯跟感覺，遇到問題再說。", value: "N" },
    ],
    culturalNote: "步驟導向 vs 摸索與直覺導向。",
    weight: 1,
  },
  {
    id: 12,
    questionId: "Q12",
    country: "Taiwan",
    dimension: "SN",
    text: "如果問你「你對5年後的自己有畫面嗎？」，你會說：",
    options: [
      { id: 'a', label: "「先把今天的事做好最重要，未來的成果都是靠每天的小習慣和待辦事項堆出來的。」", value: "S" },
      { id: 'b', label: "「我腦中有一堆版本——不同城市、不同的職涯發展、不同的生活風格，充滿各種可能。」", value: "N" },
    ],
    culturalNote: "著眼當下的累積 vs 腦中多重宇宙的願景。",
    weight: 1,
  },
  {
    id: 13,
    questionId: "Q13",
    country: "Taiwan",
    dimension: "SN",
    text: "去一間新開的創意料理餐廳，菜單全是沒看過的奇特菜名，你會：",
    options: [
      { id: 'a', label: "保守選最安全的。挑那些有寫清楚食材、接近自己熟悉味道的料理，確保不會餓肚子。", value: "S" },
      { id: 'b', label: "點名字最怪的那道！充滿好奇心，覺得就算踩雷也是個有趣的體驗，還能當作群組聊天的好素材。", value: "N" },
    ],
    culturalNote: "安全牌/確定性 vs 踩雷當有趣素材。",
    weight: 1,
  },
  {
    id: 14,
    questionId: "Q14",
    country: "Taiwan",
    dimension: "SN",
    text: "如果要你寫一篇文章或產出一段內容，你比較有把握的是：",
    options: [
      { id: 'a', label: "把真實發生的事情，用豐富的五感細節記錄下來，寫得超級具體、超有畫面感。", value: "S" },
      { id: 'b', label: "虛構一個故事或世界觀，在裡面塞滿各種隱喻、象徵意義或天馬行空的奇幻元素。", value: "N" },
    ],
    culturalNote: "真實細節描繪 vs 隱喻與概念創作。",
    weight: 1,
  },
  {
    id: 15,
    questionId: "Q15",
    country: "Taiwan",
    dimension: "SN",
    text: "在做一個沒有標準答案的選擇時，你最後拍板定案的依據通常是：",
    options: [
      { id: 'a', label: "相信「看得見的證據」。依賴具體的數據、過去的實際經驗，以及發生過的事實。", value: "S" },
      { id: 'b', label: "相信「內心的雷達」。依賴那種「雖然說不出具體原因，但就是感覺對味/對頻了」的強烈直覺。", value: "N" },
    ],
    culturalNote: "數據與經驗 vs 感覺對味的直覺。",
    weight: 1,
  },
  {
    id: 16,
    questionId: "Q16",
    country: "Taiwan",
    dimension: "SN",
    text: "對你來說，「發呆／做白日夢」的頻率比較像是：",
    options: [
      { id: 'a', label: "比較少。我的腦袋大部分時間都在處理實際的待辦事項，思考如何解決眼前的現實問題。", value: "S" },
      { id: 'b', label: "超級常！我的腦中隨時都在上演不同未來發展的迷你劇，有各種腦內小劇場。", value: "N" },
    ],
    culturalNote: "處理現實問題 vs 腦內小劇場。",
    weight: 1,
  },
  {
    id: 17,
    questionId: "Q17",
    country: "Taiwan",
    dimension: "TF",
    text: "朋友因為自己的失誤把工作搞砸，約你出來喝東西，一坐下就崩潰大哭，你的第一反應是：",
    options: [
      { id: 'a', label: "化身「解決問題的智庫」。先聽完整過程，然後開始陪他分析問題出在哪、討論下次怎麼改進最有效。", value: "T" },
      { id: 'b', label: "化身「情緒價值的提供者」。先不管對錯，陪他穩住情緒，跟他說「聽起來好沉重…你一定很難過吧」，接住他的委屈。", value: "F" },
    ],
    culturalNote: "分析與解決方案 vs 優先提供情緒價值。",
    weight: 2,
  },
  {
    id: 18,
    questionId: "Q18",
    country: "Taiwan",
    dimension: "TF",
    text: "在做一個牽涉到其他人的重要決定時，你心裡的優先排序比較是：",
    options: [
      { id: 'a', label: "這樣合不合理？對事情本身是不是最公平、最客觀，並且能達到最高的效率？", value: "T" },
      { id: 'b', label: "這樣會不會傷到誰？大家的感受怎麼樣、做這個決定會不會讓氣氛變得很尷尬？", value: "F" },
    ],
    culturalNote: "講求客觀公平 vs 在乎群體和諧與感受。",
    weight: 1,
  },
  {
    id: 19,
    questionId: "Q19",
    country: "Taiwan",
    dimension: "TF",
    text: "如果你被迫要幫公司決定一份「專案裁撤/人員縮編」的殘酷名單，你會傾向：",
    options: [
      { id: 'a', label: "理性至上。完全用過往績效、實際貢獻度，以及未來的發展潛力來做客觀排序。", value: "T" },
      { id: 'b', label: "人情考量。會忍不住想保護那些家裡負擔重、年資久，或者對公司特別有感情的夥伴。", value: "F" },
    ],
    culturalNote: "績效導向 vs 人情與情感連結。",
    weight: 1,
  },
  {
    id: 20,
    questionId: "Q20",
    country: "Taiwan",
    dimension: "TF",
    text: "你比較希望別人私底下怎麼形容你這個人？",
    options: [
      { id: 'a', label: "「這個人判斷力超強，做事非常專業、極度有能力，交給他絕對放心。」", value: "T" },
      { id: 'b', label: "「這個人超好相處，情商很高，跟他在一起總是覺得很安心、很溫暖。」", value: "F" },
    ],
    culturalNote: "被肯定能力與專業 vs 被肯定溫暖與好相處。",
    weight: 1,
  },
  {
    id: 21,
    questionId: "Q21",
    country: "Taiwan",
    dimension: "TF",
    text: "跟別人發生爭論，雙方各有立場時，你心裡最放不下、最糾結的點是：",
    options: [
      { id: 'a', label: "明明我的邏輯比較站得住腳，事情卻被對方的情緒帶偏，這點讓我超級不爽。", value: "T" },
      { id: 'b', label: "就算我知道我是對的，我也不想把關係搞僵。如果硬要講贏而傷了和氣，我心裡會覺得怪怪的。", value: "F" },
    ],
    culturalNote: "在乎邏輯正確性 vs 不想破壞關係(不燒橋)。",
    weight: 1,
  },
  {
    id: 22,
    questionId: "Q22",
    country: "Taiwan",
    dimension: "TF",
    text: "對你來說，別人給你「有用的批評與指教」應該長什麼樣子？",
    options: [
      { id: 'a', label: "直球對決。直接點出問題在哪、給我具體的改進方法就好，不用刻意包裝或顧慮我的感受。", value: "T" },
      { id: 'b', label: "高情商的三明治溝通。希望對方先肯定我的優點，再溫柔地給出建議，讓我覺得他是在「幫我」而不是「否定我」。", value: "F" },
    ],
    culturalNote: "效率直球 vs 顧及面子的溫柔建議。",
    weight: 1,
  },
  {
    id: 23,
    questionId: "Q23",
    country: "Taiwan",
    dimension: "TF",
    text: "在電影或影集裡，最容易戳中你淚點、讓你感動的橋段通常是：",
    options: [
      { id: 'a', label: "角色在絕境之下，做出了一個超有力量、合乎邏輯但卻必須犧牲自我的偉大選擇。", value: "T" },
      { id: 'b', label: "家人或摯友久別重逢的擁抱，或者是有人為了愛與友情，默默做出溫柔付出的瞬間。", value: "F" },
    ],
    culturalNote: "壯烈的邏輯犧牲 vs 深刻的情感與溫柔付出。",
    weight: 1,
  },
  {
    id: 24,
    questionId: "Q24",
    country: "Taiwan",
    dimension: "TF",
    text: "遇到完全不講理、亂發脾氣的人，你內心的自動反應機制是：",
    options: [
      { id: 'a', label: "大腦高速運轉，想用冷靜的邏輯拆解他矛盾的地方，讓他啞口無言、說不出話來。", value: "T" },
      { id: 'b', label: "會先在情緒上感到受傷或生氣，腦袋一片空白，很難在當下馬上想出漂亮的話來反擊。", value: "F" },
    ],
    culturalNote: "邏輯拆解防禦 vs 情緒先受傷。",
    weight: 1,
  },
  {
    id: 25,
    questionId: "Q25",
    country: "Taiwan",
    dimension: "JP",
    text: "出國旅行前一晚，你的行李通常長什麼樣？",
    options: [
      { id: 'a', label: "優雅的「計畫通」。幾天前就差不多收好了，甚至還有自己的打勾清單確認過一遍，享受萬無一失的安心感。", value: "J" },
      { id: 'b', label: "瀟灑的「極限打包藝術家」。地上還攤著半開的行李箱，邊想邊塞，有些東西到出門前一刻才丟進去。", value: "P" },
    ],
    culturalNote: "避開了「控制狂」，改用「計畫通」。",
    weight: 2,
  },
  {
    id: 26,
    questionId: "Q26",
    country: "Taiwan",
    dimension: "JP",
    text: "對於難得的週末，你比較喜歡怎樣的度過方式？",
    options: [
      { id: 'a', label: "提前排好行程。大概知道幾點起床、要去哪裡、吃什麼餐廳，有一個清晰的計畫框架會讓我比較有底。", value: "J" },
      { id: 'b', label: "當天早上看心情決定。覺得想出門就出門，想躺在床上廢就躺，說走就走、充滿彈性。", value: "P" },
    ],
    culturalNote: "提前排定框架 vs 當天看心情的彈性。",
    weight: 1,
  },
  {
    id: 27,
    questionId: "Q27",
    country: "Taiwan",
    dimension: "JP",
    text: "工作或日常中突然被丟進一個「緊急插隊任務」，你多半的反應是：",
    options: [
      { id: 'a', label: "覺得原本的節奏被打亂，心裡會有壓力，但還是會咬牙把它重新編排進自己的行事曆裡。", value: "J" },
      { id: 'b', label: "腎上腺素狂飆！有點被刺激到，反而覺得這種臨時救火的突發狀況，比每天照表操課還要有感覺。", value: "P" },
    ],
    culturalNote: "節奏被打亂的壓力 vs 臨時救火的腎上腺素。",
    weight: 1,
  },
  {
    id: 28,
    questionId: "Q28",
    country: "Taiwan",
    dimension: "JP",
    text: "看看你的電腦桌面或雲端資料夾，它的狀態大概是：",
    options: [
      { id: 'a', label: "數位整理大師。依照專案、日期、類型清楚分類，資料夾井然有序，好一陣子才會亂。", value: "J" },
      { id: 'b', label: "亂中有序的魔法師。一堆檔案跟截圖散在桌面上，別人看覺得很亂，但你大腦就是知道東西在哪裡。", value: "P" },
    ],
    culturalNote: "清楚分類 vs 亂中有序。",
    weight: 1,
  },
  {
    id: 29,
    questionId: "Q29",
    country: "Taiwan",
    dimension: "JP",
    text: "面對一個還沒做最後決定的選項（例如要不要去某個聚會、買某個東西），你的感受比較像：",
    options: [
      { id: 'a', label: "事情懸在那裡會讓我有點焦慮。我寧願快點拍板定案，就算之後要微調也沒關係，先定下來再說。", value: "J" },
      { id: 'b', label: "能多留幾個選項就多留。不到最後一刻不想把話說死，喜歡保留調整空間到極限。", value: "P" },
    ],
    culturalNote: "提早決定的安心感 vs 保留選項的開放性。",
    weight: 1,
  },
  {
    id: 30,
    questionId: "Q30",
    country: "Taiwan",
    dimension: "JP",
    text: "談到職場或生活中的「規則與SOP」，你心裡比較貼近哪一句話：",
    options: [
      { id: 'a', label: "規則是為了建立效率與和諧。有明確的規則大家才知道怎麼配合，事情推動起來才會順利。", value: "J" },
      { id: 'b', label: "規則只是一種參考。遇到特殊狀況時，人的彈性跟發揮創意解決問題的能力，比死守規則重要多了。", value: "P" },
    ],
    culturalNote: "規則帶來效率 vs 彈性與創意至上。",
    weight: 1,
  },
  {
    id: 31,
    questionId: "Q31",
    country: "Taiwan",
    dimension: "JP",
    text: "努力完成一個專案或度過忙碌的一週後，讓你最「有感/最爽」的瞬間是：",
    options: [
      { id: 'a', label: "把 To-do list 上最後一格打勾、把檔案存檔結案的那一刻，那種徹底清空的清爽感！", value: "J" },
      { id: 'b', label: "犒賞自己的 Treat yo' self 瞬間！或者是在過程中突然想到一個超棒的新做法，覺得自己又進化解鎖了一關。", value: "P" },
    ],
    culturalNote: "加入了使用者建議的 Treat yo' self 概念取代難懂的 Girl Math。",
    weight: 1,
  },
  {
    id: 32,
    questionId: "Q32",
    country: "Taiwan",
    dimension: "JP",
    text: "如果要把你對「人生這場遊戲」的態度濃縮成一種哲學，你覺得哪一個最貼切？",
    options: [
      { id: 'a', label: "人生是一張「藍圖」。喜歡設定明確的里程碑，一步步打怪升級，享受把不確定性降到最低的「絕對掌控感」。", value: "J" },
      { id: 'b', label: "人生是一場「體驗」。比起死板的目標，更相信「船到橋頭自然直」，享受沿途開盲盒的驚喜與各種「支線任務」。", value: "P" },
    ],
    culturalNote: "人生藍圖與掌控感 vs 開盲盒與支線任務。",
    weight: 1,
  },
  {
    id: 33,
    questionId: "Q33",
    country: "Taiwan",
    dimension: "AT",
    text: "事情突然大反轉、不照你的計畫走時，你內心的第一反應是：",
    options: [
      { id: 'a', label: "啟動 Lucky Vicky 的正向轉念！深呼吸一下想：「好，那接下來我可以怎麼辦？說不定這樣更好！」", value: "A" },
      { id: 'b', label: "先經歷一陣焦慮。腦中開始瘋狂重播，檢討是不是自己哪裡沒做好才導致這個結果。", value: "Turbulent" },
    ],
    culturalNote: "加入了使用者提議的「Lucky Vicky (張員瑛轉念法)」正向思考。",
    weight: 2,
  },
  {
    id: 34,
    questionId: "Q34",
    country: "Taiwan",
    dimension: "AT",
    text: "對於自己的能力與表現，你心裡比較常出現的聲音是：",
    options: [
      { id: 'a', label: "「大致上我相信自己，就算遇到完全不會的新東西，我也能慢慢學起來。」自帶健康的自我肯定感。", value: "A" },
      { id: 'b', label: "「我好像還不夠好。」經常需要再拿出具體成績，或者被別人大力肯定後，心裡才會覺得比較踏實。", value: "Turbulent" },
    ],
    culturalNote: "自我肯定與信任 vs 需要外界肯定與完美主義。",
    weight: 1,
  },
  {
    id: 35,
    questionId: "Q35",
    country: "Taiwan",
    dimension: "AT",
    text: "如果在群組裡說錯話，或者講了一個瞬間冷場的爛梗，過後你會：",
    options: [
      { id: 'a', label: "擁有強大的心理防禦力。當場笑一笑、發個貼圖帶過，之後也完全不會把這件事放在心上。", value: "A" },
      { id: 'b', label: "回家後大腦會一直不受控地回想那一幕，經歷嚴重的「尷尬癌發作」，甚至會懊惱破防好一陣子。", value: "Turbulent" },
    ],
    culturalNote: "心理防禦/不在乎 vs 尷尬癌/反覆內耗。",
    weight: 1,
  },
  {
    id: 36,
    questionId: "Q36",
    country: "Taiwan",
    dimension: "AT",
    text: "當一個重要專案的 Deadline 快到了，被巨大的壓力推著跑時，你的狀態是：",
    options: [
      { id: 'a', label: "反而會進入極致的「高專注模式」。其實你心裡知道，自己在有點壓力的情況下反而跑得更快、效率更好。", value: "A" },
      { id: 'b', label: "容易感到心慌、甚至影響睡眠。會因為超級害怕自己出錯或來不及交件，而產生極大的精神壓力。", value: "Turbulent" },
    ],
    culturalNote: "壓力轉化為專注力 vs 壓力引發焦慮與自我要求。",
    weight: 1,
  },
  {
    id: 37,
    questionId: "Q37",
    country: "Taiwan",
    dimension: "AT",
    text: "對於周遭「別人的情緒」，你自認你的抵抗力有多高？",
    options: [
      { id: 'a', label: "邊界感極佳。我能清楚分辨「那是他的情緒，不是我的」，比較不容易被別人的負能量拖走。", value: "A" },
      { id: 'b', label: "天生的高敏感天線。很容易被現場的氣氛影響，身邊的人一陷入低氣壓，我的心情也會跟著沉下去。", value: "Turbulent" },
    ],
    culturalNote: "情緒邊界感 vs 高共情與易受影響。",
    weight: 1,
  },
  {
    id: 38,
    questionId: "Q38",
    country: "Taiwan",
    dimension: "AT",
    text: "面對未來可能發生的各種風險與不確定性，你通常的心態是：",
    options: [
      { id: 'a', label: "「船到橋頭自然直，真的發生了再說，到時候總會有辦法處理的。」主打一個兵來將擋的樂觀。", value: "A" },
      { id: 'b', label: "超級危機管理師。會先在腦袋裡把最糟的劇本都演過一遍，預想好各種備案跟退路才會安心。", value: "Turbulent" },
    ],
    culturalNote: "樂觀面對未知 vs 災難化思考與嚴謹備案。",
    weight: 1,
  },
  {
    id: 39,
    questionId: "Q39",
    country: "Taiwan",
    dimension: "AT",
    text: "談到你現在的人生狀態與成就，你心裡的感覺比較接近：",
    options: [
      { id: 'a', label: "雖然還有很多想達成的目標，但大致上我能欣賞並滿意現在的自己和目前的生活樣貌。", value: "A" },
      { id: 'b', label: "總覺得哪裡還不夠好。常常會在心裡對自己說「再撐一下、還要再更好一點」，有著強烈的自我驅動力。", value: "Turbulent" },
    ],
    culturalNote: "知足與自我接納 vs 永不滿足的進步渴望。",
    weight: 1,
  },
  {
    id: 40,
    questionId: "Q40",
    country: "Taiwan",
    dimension: "AT",
    text: "當有人評論你的心血作品，並說「我覺得這裡可以再調整一下」時，你比較像是：",
    options: [
      { id: 'a', label: "自帶「不沾鍋屬性」。大腦會自動把這句話拆解成具體建議，直接拿來當作修正的客觀參考，不帶任何情緒。", value: "A" },
      { id: 'b', label: "會先感受到一點點被否定的刺痛。需要一點時間消化情緒，轉念成「這是為了讓作品變更好」後才能重新出發。", value: "Turbulent" },
    ],
    culturalNote: "客觀接收回饋 vs 情緒先受傷再轉念。",
    weight: 1,
  }
];
