/* eslint-disable */
// Auto-generated by scripts/generate-v2-tw-quiz.mjs
// Source: /Users/pensoair/Obsidian-Vaults/Penso-SSOT/07_專案工坊/Subdomain_kiwimu.com/Kiwimu_MBTI_Lab_內容庫/2026_H1_跨國升級版/MBTI_Question_Bank_2026_Taiwan.md

export type V2QuestionDimension = 'EI' | 'SN' | 'TF' | 'JP' | 'AT';
export type V2QuestionValue = 'E' | 'I' | 'S' | 'N' | 'T' | 'F' | 'J' | 'P' | 'A' | 'Turbulent';

export interface V2GeneratedQuestionOption {
  id: 'a' | 'b';
  label: string;
  value: V2QuestionValue;
}

export interface V2GeneratedQuestion {
  id: number;
  questionId: string;
  country: string;
  dimension: V2QuestionDimension;
  text: string;
  options: [V2GeneratedQuestionOption, V2GeneratedQuestionOption];
  culturalNote: string;
  weight: number;
}

export const V2_TW_QUESTION_SOURCE = "/Users/pensoair/Obsidian-Vaults/Penso-SSOT/07_專案工坊/Subdomain_kiwimu.com/Kiwimu_MBTI_Lab_內容庫/2026_H1_跨國升級版/MBTI_Question_Bank_2026_Taiwan.md";

export const V2_TAIWAN_QUESTIONS: V2GeneratedQuestion[] = [
  {
    id: 1,
    questionId: "Q01",
    country: "Taiwan",
    dimension: "EI",
    text: "忙了一整週，終於有空休息。哪種安排比較能讓你恢復精神？",
    options: [
      { id: 'a', label: "約朋友吃飯、走走，在互動中慢慢充電。", value: "E" },
      { id: 'b', label: "留一段不被打擾的時間，自己看劇、閱讀或放空。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 2,
  },
  {
    id: 2,
    questionId: "Q02",
    country: "Taiwan",
    dimension: "EI",
    text: "來到大多是陌生人的聚會，你通常怎麼開始？",
    options: [
      { id: 'a', label: "找個話題和身邊的人聊聊，邊聊邊熟悉。", value: "E" },
      { id: 'b', label: "先觀察現場，從認識的人或小範圍對話開始。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 3,
    questionId: "Q03",
    country: "Taiwan",
    dimension: "EI",
    text: "休假時收到朋友臨時的咖啡邀約，你比較接近哪個反應？",
    options: [
      { id: 'a', label: "想到能見面聊聊，精神就來了，想加入。", value: "E" },
      { id: 'b', label: "先感受自己還有沒有互動的力氣，再決定。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 4,
    questionId: "Q04",
    country: "Taiwan",
    dimension: "EI",
    text: "看到想分享的日常，你通常會怎麼做？",
    options: [
      { id: 'a', label: "發動態或丟進群組，想聽聽大家的回應。", value: "E" },
      { id: 'b', label: "先留給自己，或只傳給少數熟悉的人。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 5,
    questionId: "Q05",
    country: "Taiwan",
    dimension: "EI",
    text: "在 LINE 群組或聚會裡討論事情，你比較習慣：",
    options: [
      { id: 'a', label: "把還沒成形的想法說出來，邊聊邊整理。", value: "E" },
      { id: 'b', label: "先聽大家說，等想法比較完整再開口。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 6,
    questionId: "Q06",
    country: "Taiwan",
    dimension: "EI",
    text: "和朋友的關係慢慢變熟時，你通常比較依靠：",
    options: [
      { id: 'a', label: "常見面、常聊天，在日常互動裡累積熟悉感。", value: "E" },
      { id: 'b', label: "少數深入的對話，即使不常見面也能連結。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 7,
    questionId: "Q07",
    country: "Taiwan",
    dimension: "EI",
    text: "發現一間想去的餐廳或展覽，你第一個念頭是：",
    options: [
      { id: 'a', label: "找幾個人一起去，有人分享感受更有趣。", value: "E" },
      { id: 'b', label: "自己去，或約一位熟悉的人，按自己的步調看。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 8,
    questionId: "Q08",
    country: "Taiwan",
    dimension: "EI",
    text: "遇到一件想不通的事，你比較常怎麼找答案？",
    options: [
      { id: 'a', label: "找人聊聊，說出來之後才知道自己怎麼想。", value: "E" },
      { id: 'b', label: "先自己想一輪，寫下來或沉澱後再和人討論。", value: "I" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 9,
    questionId: "Q09",
    country: "Taiwan",
    dimension: "SN",
    text: "朋友說起一件新鮮事，你比較先注意：",
    options: [
      { id: 'a', label: "事情怎麼發生、誰做了什麼，想把細節弄清楚。", value: "S" },
      { id: 'b', label: "背後可能的原因，以及它和其他事情的關聯。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 2,
  },
  {
    id: 10,
    questionId: "Q10",
    country: "Taiwan",
    dimension: "SN",
    text: "第一次走進一間咖啡廳，你比較先留意：",
    options: [
      { id: 'a', label: "光線、座位、聲音和菜單等眼前的細節。", value: "S" },
      { id: 'b', label: "整體氛圍，還有這個空間讓我想到的故事。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 11,
    questionId: "Q11",
    country: "Taiwan",
    dimension: "SN",
    text: "學一個新的 App 或工具，你比較習慣：",
    options: [
      { id: 'a', label: "照著範例操作一次，從具體步驟開始熟悉。", value: "S" },
      { id: 'b', label: "先理解它能做到什麼，再試不同的用法。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 12,
    questionId: "Q12",
    country: "Taiwan",
    dimension: "SN",
    text: "想到五年後的生活，你腦中比較容易出現：",
    options: [
      { id: 'a', label: "住在哪裡、做什麼工作，幾個具體的生活畫面。", value: "S" },
      { id: 'b', label: "想走向的方向，以及幾種還沒定下來的可能。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 13,
    questionId: "Q13",
    country: "Taiwan",
    dimension: "SN",
    text: "遇到一份看不懂的創意料理菜單，你通常會：",
    options: [
      { id: 'a', label: "先問食材和做法，想像實際吃起來的味道。", value: "S" },
      { id: 'b', label: "先被概念或組合吸引，想試試沒吃過的搭配。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 14,
    questionId: "Q14",
    country: "Taiwan",
    dimension: "SN",
    text: "要寫一篇文章，你比較容易從哪裡開始？",
    options: [
      { id: 'a', label: "親身經驗和具體例子，把事情描述清楚。", value: "S" },
      { id: 'b', label: "一個觀點或聯想，再找能把它說明的素材。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 15,
    questionId: "Q15",
    country: "Taiwan",
    dimension: "SN",
    text: "沒有標準答案的選擇，你最後比較依靠：",
    options: [
      { id: 'a', label: "已知資訊、過往經驗和實際可行性。", value: "S" },
      { id: 'b', label: "對整體走向的判斷，以及尚未被證實的可能。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 16,
    questionId: "Q16",
    country: "Taiwan",
    dimension: "SN",
    text: "暫時沒有事情要做時，你的思緒常走向哪裡？",
    options: [
      { id: 'a', label: "眼前的生活、接下來要做的事或最近的經驗。", value: "S" },
      { id: 'b', label: "不同的假設、未來的場景或突然冒出的聯想。", value: "N" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 17,
    questionId: "Q17",
    country: "Taiwan",
    dimension: "TF",
    text: "朋友因為工作失誤很難過，來找你聊天。你通常先做什麼？",
    options: [
      { id: 'a', label: "聽清楚發生什麼事，陪他找出可以處理的部分。", value: "T" },
      { id: 'b', label: "先了解他現在的感受，讓他知道有人陪著。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 2,
  },
  {
    id: 18,
    questionId: "Q18",
    country: "Taiwan",
    dimension: "TF",
    text: "做一個會影響其他人的決定時，你比較先衡量：",
    options: [
      { id: 'a', label: "判斷標準是否一致，理由能不能說得通。", value: "T" },
      { id: 'b', label: "每個人的需要，以及決定對彼此關係的影響。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 19,
    questionId: "Q19",
    country: "Taiwan",
    dimension: "TF",
    text: "小組資源有限，需要調整分工。你比較先考慮：",
    options: [
      { id: 'a', label: "按照任務需求和每個人的專長重新安排。", value: "T" },
      { id: 'b', label: "先了解各自的負擔，再協調大家能接受的安排。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 20,
    questionId: "Q20",
    country: "Taiwan",
    dimension: "TF",
    text: "面對一個重要但兩難的決定，你最先問自己：",
    options: [
      { id: 'a', label: "哪個選擇的理由更充分，長期結果更合理？", value: "T" },
      { id: 'b', label: "哪個選擇更符合我在乎的價值和人的需要？", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 21,
    questionId: "Q21",
    country: "Taiwan",
    dimension: "TF",
    text: "和在乎的人意見不同時，你最想先釐清：",
    options: [
      { id: 'a', label: "我們的說法哪裡有矛盾，判斷依據是什麼。", value: "T" },
      { id: 'b', label: "彼此為什麼在意這件事，有沒有被理解。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 22,
    questionId: "Q22",
    country: "Taiwan",
    dimension: "TF",
    text: "收到修改建議時，哪種方式比較方便你吸收？",
    options: [
      { id: 'a', label: "直接說明問題、理由和可行的修改方向。", value: "T" },
      { id: 'b', label: "先理解我的用意，再一起討論可以怎麼調整。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 23,
    questionId: "Q23",
    country: "Taiwan",
    dimension: "TF",
    text: "看電影或影集時，哪種衝突更容易讓你反覆想？",
    options: [
      { id: 'a', label: "角色如何在兩難中取捨，選擇是否前後一致。", value: "T" },
      { id: 'b', label: "角色之間的誤解、牽掛，以及沒有說出口的感受。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 24,
    questionId: "Q24",
    country: "Taiwan",
    dimension: "TF",
    text: "遇到一場語氣激動的爭論，你通常先注意：",
    options: [
      { id: 'a', label: "先把主張和事實分開，找出可以討論的問題。", value: "T" },
      { id: 'b', label: "先留意彼此的情緒，確認現在適不適合繼續談。", value: "F" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 25,
    questionId: "Q25",
    country: "Taiwan",
    dimension: "JP",
    text: "旅行出發前，你通常怎麼準備行李？",
    options: [
      { id: 'a', label: "提前整理一份清單，分幾次把東西收好。", value: "J" },
      { id: 'b', label: "接近出發時再集中打包，想到需要什麼就加入。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 2,
  },
  {
    id: 26,
    questionId: "Q26",
    country: "Taiwan",
    dimension: "JP",
    text: "難得有一個空白週末，你比較喜歡：",
    options: [
      { id: 'a', label: "先安排幾件想做的事，心裡有個大致順序。", value: "J" },
      { id: 'b', label: "保留空白，當天再看精神和心情決定。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 27,
    questionId: "Q27",
    country: "Taiwan",
    dimension: "JP",
    text: "突然多了一件緊急任務，你通常會：",
    options: [
      { id: 'a', label: "先重排優先順序，讓新任務進入原本的計畫。", value: "J" },
      { id: 'b', label: "先處理眼前最需要的部分，其他事情邊做邊調整。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 28,
    questionId: "Q28",
    country: "Taiwan",
    dimension: "JP",
    text: "整理電腦檔案時，你比較習慣：",
    options: [
      { id: 'a', label: "有固定的分類和命名方式，方便之後查找。", value: "J" },
      { id: 'b', label: "依照當下工作方式放置，需要時再整理歸檔。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 29,
    questionId: "Q29",
    country: "Taiwan",
    dimension: "JP",
    text: "一件事還沒做最後決定時，你比較接近：",
    options: [
      { id: 'a', label: "想早點定下方向，之後有變化再調整。", value: "J" },
      { id: 'b', label: "想多留幾個選項，等資訊更完整再決定。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 30,
    questionId: "Q30",
    country: "Taiwan",
    dimension: "JP",
    text: "面對工作中的規則或流程，你比較傾向：",
    options: [
      { id: 'a', label: "先依照共同流程執行，讓大家容易配合。", value: "J" },
      { id: 'b', label: "看情況調整方法，替當下的問題找到合適解法。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 31,
    questionId: "Q31",
    country: "Taiwan",
    dimension: "JP",
    text: "做完一個專案，哪個瞬間更讓你有滿足感？",
    options: [
      { id: 'a', label: "把待辦一項項完成，確認整件事順利收尾。", value: "J" },
      { id: 'b', label: "過程中找到新做法，發現還可以延伸的可能。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 32,
    questionId: "Q32",
    country: "Taiwan",
    dimension: "JP",
    text: "安排接下來一年的生活，你比較喜歡：",
    options: [
      { id: 'a', label: "設定幾個里程碑，知道自己正往哪裡前進。", value: "J" },
      { id: 'b', label: "留著大方向，隨新的機會和經驗調整路線。", value: "P" },
    ],
    culturalNote: "生活反應對照；兩種選擇無優劣。",
    weight: 1,
  },
  {
    id: 33,
    questionId: "Q33",
    country: "Taiwan",
    dimension: "AT",
    text: "最近事情不照預期發展時，你比較常：",
    options: [
      { id: 'a', label: "接受有些事無法控制，把注意力轉向下一步。", value: "A" },
      { id: 'b', label: "先回想哪裡可以做得更好，想清楚才比較安心。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 2,
  },
  {
    id: 34,
    questionId: "Q34",
    country: "Taiwan",
    dimension: "AT",
    text: "最近面對不熟悉的任務，你心裡比較接近：",
    options: [
      { id: 'a', label: "相信自己可以逐步學會，先開始再修正。", value: "A" },
      { id: 'b', label: "想先確認準備夠不夠，得到回饋才比較踏實。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  },
  {
    id: 35,
    questionId: "Q35",
    country: "Taiwan",
    dimension: "AT",
    text: "最近在群組裡說錯話或遇到冷場，事後你通常：",
    options: [
      { id: 'a', label: "稍微想一下就放下，繼續做原本的事。", value: "A" },
      { id: 'b', label: "會回想當時的反應，需要一點時間才能放下。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  },
  {
    id: 36,
    questionId: "Q36",
    country: "Taiwan",
    dimension: "AT",
    text: "最近期限逼近時，你比較常出現哪種反應？",
    options: [
      { id: 'a', label: "把注意力收回眼前的步驟，壓力相對容易消化。", value: "A" },
      { id: 'b', label: "反覆確認有沒有遺漏，需要多一點時間安定下來。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  },
  {
    id: 37,
    questionId: "Q37",
    country: "Taiwan",
    dimension: "AT",
    text: "最近身邊的人心情不好時，你比較接近：",
    options: [
      { id: 'a', label: "能留意對方的感受，同時維持自己的步調。", value: "A" },
      { id: 'b', label: "容易跟著現場氣氛起伏，之後需要整理心情。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  },
  {
    id: 38,
    questionId: "Q38",
    country: "Taiwan",
    dimension: "AT",
    text: "最近想到尚未發生的風險，你比較常：",
    options: [
      { id: 'a', label: "先做必要準備，剩下的等有新資訊再處理。", value: "A" },
      { id: 'b', label: "多推演幾種情況，有備案才比較能放心。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  },
  {
    id: 39,
    questionId: "Q39",
    country: "Taiwan",
    dimension: "AT",
    text: "回看最近的生活和表現，你比較常感覺：",
    options: [
      { id: 'a', label: "還有想調整的地方，但也能接受目前的進度。", value: "A" },
      { id: 'b', label: "很快注意到可以更好的地方，想再多推進一些。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  },
  {
    id: 40,
    questionId: "Q40",
    country: "Taiwan",
    dimension: "AT",
    text: "最近有人建議修改你的作品，你通常會：",
    options: [
      { id: 'a', label: "先把回饋當成可用資訊，再決定採用哪些。", value: "A" },
      { id: 'b', label: "先感受到一點壓力，消化後再整理修改方向。", value: "Turbulent" },
    ],
    culturalNote: "近期自我回應傾向；A/T 不代表能力高低。",
    weight: 1,
  }
];
